### ISSUE TITLE
Failing PR builds

### ISSUE THREAD

**Issue by bmayen** [AngularClass/angular2-webpack-starter#1464]
There are a handful of PRs which have failed due to internal Travis errors. Could somebody with access re-trigger these builds so they can hopefully pass?

**Comment by katallaxie** [comment]
I have merged quite some of PR's, and ci should be fixed.

**Comment by bmayen** [comment]
Builds are still failing. Randomly hanging on e2e tests.

Starting up http-server, serving dist
Available on:
  http://127.0.0.1:3000
  http://10.10.8.57:3000
Hit CTRL-C to stop the server
> angular2-webpack-starter@5.4.1 protractor /home/travis/build/AngularClass/angular2-webpack-starter
> protractor
(node:5827) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:58:41] I/direct - Using ChromeDriver directly...
[17:58:41] I/launcher - Running 1 instances of WebDriver
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
