### ISSUE TITLE
"Unexpected token case" when running e2e

### ISSUE THREAD

**Issue by poznyakovskiy** [AngularClass/angular2-webpack-starter#264]
When I run e2e (`npm run e2e`), protractor stops with the message

```
> ts-node node_modules/.bin/protractor --specs src/**/**.e2e.ts,src/**/*.e2e.ts

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at Object.<anonymous> (C:\Dev\angular2-webpack-starter\node_modules\ts-node\src\bin\ts-node.ts:121:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by scottmcdonnell** [comment]
+1

**Comment by imeninnik** [comment]
got the same.
win 10.
thought `npm run e2e:live` works

**Comment by dsebastien** [comment]
Same issue here w/ Windows 10 (x64).
I don't think that protractor is actually executed, the issue must be with ts-node when it tries to load the protractor script.

What is the benefit of using `ts-node node_modules/.bin/protractor` rather than simply protractor in the script?

**Comment by gdi2290** [comment]
the problem is `src/**/**.e2e.ts,src/**/*.e2e.ts` in windows which I fixed in the latest release
https://github.com/AngularClass/angular2-webpack-starter/blob/master/package.json#L31

**Comment by dsebastien** [comment]
I still get the error even without the src/**....:

Here's the script I'm using: `"e2e": "ts-node node_modules/.bin/protractor",`
`

**Comment by samvloeberghs** [comment]
same here, running it without ts-node for now.

**Comment by jmiazga** [comment]
+1. Seeing the same 'SyntaxError: Unexpected token case' error.

**Comment by daddywoodland** [comment]
+1

Reverted to "e2e": "protractor protractor.conf.js"

Also needed to add 'use strict' to .e2e files

**Comment by Eru5** [comment]
+1

**Comment by yaroslavya** [comment]
Doesnt work with `"e2e":"protractor protractor.conf.js"` for me. Chrome opens and gets stuck with the `data:,` in the url. If I close the browser I see that all the assertions for all the tests failed. Im on windows, maybe thats the reason. 

Note, that it only fails like that after I add `'use strict';` to the top of the e2e test. If I just run it I have the following error: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.

I only cloned the repo, made npm install and run the e2e as described in the doc. So I had the webdriver up and running with `npm run webdriver:start`

**Comment by vespertilian** [comment]
I am getting the same error. I think dropping the `ts-node` and running protractor directly works a little because node works with most of the ES6 syntax that TS supports.

**Comment by czebe** [comment]
+1
I'm also stuck with data:; in Chrome, and script timeout. Running on OSX.
