### ISSUE TITLE
EPEERINVALID during npm install (Quick start guide)

### ISSUE THREAD

**Issue by MartinMa** [AngularClass/angular2-webpack-starter#501]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When I run `npm install` on a fresh git clone, I get the following **peerDependencies** error.
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.14 wants rxjs@5.0.0-beta.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Martin\Documents\Projects\angular2-webpack-starter\npm-debug.log
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Follow the *Quick start* guide from `README.md`. The error will show up in the console after calling `npm install`.

* **What is the expected behavior?**
No EPEERINVALID error message.

* **What is the motivation / use case for changing the behavior?**
Getting started process shouldn't lead to errors.

* **Please tell us about your environment:**
Windows 8.1
node v4.4.2
npm  v2.15.0

- Angular version: 2.0.0-beta.14
- Browser: [not applicable]

* **Other information**
I seem to have fixed it by switching from `"rxjs": "5.0.0-beta.4"` to `"rxjs": "5.0.0-beta.2"`.

**Comment by roelleor** [comment]
same problem here:
mac osx
node v4.1.2
npm  v2.14.4

**Comment by CristyTarantino** [comment]
:+1:

**Comment by gdi2290** [comment]
if yu update to npm 3 via `npm install -g npm@3` then you should be ok. I can also fix it for npm 2 users

**Comment by MartinMa** [comment]
@gdi2290 Thanks for the info. I upgraded to npm 3 (v3.8.7) via `npm-windows-upgrade` (it seems to be a special package for this purpose) and ran `npm install` again (after clearing the node_modules folder and the npm cache). I don't get an error now and the demo project seems to work, but I still get a warning:
`UNMET PEER DEPENDENCY rxjs@5.0.0-beta.4`
and
`npm WARN angular2@2.0.0-beta.14 requires a peer of rxjs@5.0.0-beta.2 but none was installed.`

I would suggest to either update the guide, so people will know, that they need npm version >= 3 or update the dependencies in `package.json` like proposed (when that's the correct fix).

**Comment by MartinMa** [comment]
Fixed by a37c92b9b446faa68b63b389e584842963240b4a and 1205e1a3bdd1c693a8e31d2d38548d11e8333123 (downgrade rxjs). Closing. :beer: :+1:

**Comment by miteshpant** [comment]
Still getting this issue 

MITESH@MITESH-THINK MINGW32 ~/Desktop/development/angular-quickstart
$ npm install -g npm
C:\Users\MITESH\AppData\Roaming\npm\npm -> C:\Users\MITESH\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@4.0.5 C:\Users\MITESH\AppData\Roaming\npm\node_modules\npm

MITESH@MITESH-THINK MINGW32 ~/Desktop/development/angular-quickstart
$ npm install
npm WARN package.json angular-quickstart@1.0.0 No description
npm WARN package.json angular-quickstart@1.0.0 No repository field.
npm WARN package.json angular-quickstart@1.0.0 No README data
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.4.1 wants rxjs@^5.0.1
npm ERR! peerinvalid Peer @angular/http@2.4.1 wants rxjs@^5.0.1
npm ERR! peerinvalid Peer @angular/router@3.4.1 wants rxjs@^5.0.1
npm ERR! peerinvalid Peer angular-in-memory-web-api@0.1.17 wants rxjs@5.0.0-rc.4

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MITESH\Desktop\development\angular-quickstart\npm-debug.log

**Comment by mukesh-yadav2170** [comment]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vipulsharma/mukesh/ionic2/Ionic2TabTranlation/npm-debug.log


This error has occurred several time on my mac ox 
Finding many solutions but not work, Simply I update npm version "v2.15.8" to npm version "3" 
and work for me 

Amazing it work

**Comment by dprager** [comment]
Wow, this helped me out so much clearifying signalr and combining it with Angular 2. Awesome post!!

Thank you for this
