### ISSUE TITLE
How to use ng2-bootstrap Bootstrap 4 and Sass

### ISSUE THREAD

**Issue by painhardcore** [AngularClass/angular2-webpack-starter#984]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

Need some guide how use this starter pack with components in header.
Wiki chapters like "How to use Bootstrap 4 and Sass (and jQuery)" is outdated.
And big question for beginners is "How to include vendor styles like css styles or other css"
My point that starter pack needs to be more simple to use and scale and more articles "how to use *" like how to adjust webpack,plugins etc.

**Comment by regenrek** [comment]
Hi I also struggled with boostrap implementation.

I have a fork where I implemented bootstrap 4. Maybe it helps: https://github.com/regenrek/angular2-webpack-extended

And here is a issue thread where we discuss a bit about the use of 
bootstrap 4: https://github.com/AngularClass/angular2-webpack-starter/issues/924

Regards

**Comment by painhardcore** [comment]
@regenrek thanks for the tips.
But i still have some problems and don't know what's wrong with it
```bash
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error:
Could not find bootstrap version: '3'. Did you install it?
The package is 'bootstrap' for bootstrap v4 and 'bootstrap-sass' for v3.

    at Object.module.exports.pitch (/Users//angular2-webpack-starter/node_modules/bootstrap-loader/lib/bootstrap.loader.js:140:11)
 @ ./~/bootstrap-loader/loader.js 1:17-61
 @ ./src/vendor.browser.ts
 @ multi vendor
```
I've tried to copy webpack.common.js for my project, but no luck.
And [wiki article](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)) not doing right job anymore.
That's why i proposed to make this pack with Bootstrap 4 ready with every update

**Comment by d3viant0ne** [comment]
Updating the wiki doc would be appreciated. If you aren't interested in adding the documentation, [this](https://github.com/akveo/ng2-admin) is based off the starter & runs bootstrap4.
